### ISSUE TITLE
MIUI12.2.2稳定版(MIUI12.2.2.0 RJKCNXM) 类名或URL均不起作用

### ISSUE THREAD

**Issue by Proanx** [lamprose/MIUIQuickOpen#2]
用的git页面最新的release（1.2）
包名/类名或者URL均无效，会正常打开原功能
![QQ图片20210507155057](https://user-images.githubusercontent.com/39716510/117416518-faf6a780-af08-11eb-9aa8-dc7306188ad6.jpg)
![QQ图片20210507155100](https://user-images.githubusercontent.com/39716510/117416530-fdf19800-af08-11eb-9584-30b03afd0d31.jpg)

**Comment by lamprose** [comment]
请提供LSPosed的相关日志

**Comment by Proanx** [comment]
[LSPosed_Modules_20210507_162258.log](https://github.com/lamprose/MIUIQuickOpen/files/6440135/LSPosed_Modules_20210507_162258.log)
日志内容前部分是手机重启之后修改设置并重启UI后成功跑动，再次修改并重启UI以后开始失效，见日志底部报错null部分

**Comment by lamprose** [comment]
看到是拿到数据了的  日志输出也都是正常的  按理说应该会生效的

**Comment by lamprose** [comment]
意思是重启手机后第一次修改设置后重启系统界面是可以成功运行的
后面修改设置重启系统界面就不行了  对吧

**Comment by Proanx** [comment]
> 意思是重启手机后第一次修改设置后重启系统界面是可以成功运行的
> 后面修改设置重启系统界面就不行了 对吧

具体复现步骤我还没搞明白，目前测试是随机有效，成功率差不多1/4

**Comment by lamprose** [comment]
新版本应该修复了这个问题  你试试吧

**Comment by Proanx** [comment]
> 新版本应该修复了这个问题 你试试吧

已解决
